server:
  port: 9092
spring:
  datasource:
    url: jdbc:mysql://123:3306/wheel-mysql?serverTimezone=CTT&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
mybatis:
  mapper-locations: classpath:mappers/*.xml
